In [12]:
import pandas as pd
from scipy import stats

In [13]:
df1 = pd.read_excel("../Data/DDW_PCA0000_2011_Indiastatedist.xlsx")
df1 = df1[(df1["TRU"] == "Total") & (df1["Level"] == "STATE")]

In [14]:
cols = ["state-code", "area-name", "Total", "age-groups", "males_2", "females_2", "males_3", "females_3"]
df2 = pd.read_excel("../Data/DDW-C18-0000.xlsx", skiprows = [0,1,2,3,5], usecols = [0, 2, 3, 4, 6, 7, 9, 10], names = cols)
df2 = df2[(df2['Total'] == "Total") & (df2["age-groups"] == "Total")]

In [15]:
output = {"state-name" : [], "percent-one_m" : [], "percent-two_m" : [], "percent-three_m" : [], "percent-one_f" : [], "percent-two_f" : [], "percent-three_f" : [], "M/F": [], "M/F_1": [], "M/F_2": [], "M/F_3": []}
for idx,row in df1.iterrows():
    temp = df2[df2['state-code'] == row["State"]]
    output["state-name"].append(row["Name"])
    
    male_mono = int(row["TOT_M"] - temp["males_2"])
    output["percent-one_m"].append(male_mono/row["TOT_M"] * 100)
    male_bi = int(temp["males_2"] - temp["males_3"])
    output["percent-two_m"].append(male_bi/row["TOT_M"] * 100)
    male_tri = int(temp["males_3"])
    output["percent-three_m"].append(male_tri/row["TOT_M"] * 100)
    
    female_mono = int(row["TOT_F"] - temp["females_2"])
    output["percent-one_f"].append(female_mono/row["TOT_F"] * 100)
    female_bi = int(temp["females_2"] - temp["females_3"])
    output["percent-two_f"].append(female_bi/row["TOT_F"] * 100)
    female_tri = int(temp["females_3"])
    output["percent-three_f"].append(female_tri/row["TOT_F"] * 100)
    
    output["M/F"].append(row["TOT_M"]/row["TOT_F"])
    output["M/F_1"].append(male_mono/female_mono)
    output["M/F_2"].append(male_bi/female_bi)
    output["M/F_3"].append(male_tri/female_tri)

In [16]:
df = pd.DataFrame(output)

In [17]:
pval = []
for idx, row in df.iterrows():
    l1 = [row["M/F_1"], row["M/F_2"], row["M/F_3"]]
    l2 = [row["M/F"], row["M/F"], row["M/F"]]
    val = stats.ttest_ind(l1, l2, equal_var=False)
    pval.append(val[1])
df["pval"] = pval
df

,state-name,percent-one_m,percent-two_m,percent-three_m,percent-one_f,percent-two_f,percent-three_f,M/F,M/F_1,M/F_2,M/F_3,pval
0,JAMMU & KASHMIR,45.264207,35.780514,18.955279,56.811956,28.995278,14.192766,1.125414,0.896659,1.388774,1.503057,0.537034
1,HIMACHAL PRADESH,80.356377,13.885860,5.757763,83.482596,12.177476,4.339928,1.029309,0.990764,1.173711,1.365580,0.306330
2,PUNJAB,50.242833,19.811803,29.945363,56.111899,17.589983,26.298118,1.117186,1.000333,1.258300,1.272127,0.568812
3,CHANDIGARH,44.391497,24.857964,30.750539,45.865830,23.926519,30.207651,1.222997,1.183684,1.270607,1.244976,0.733277
4,UTTARAKHAND,80.871829,16.996333,2.131838,84.338870,14.078980,1.582150,1.038245,0.995564,1.253383,1.398963,0.270833
5,HARYANA,75.859880,19.092018,5.048102,80.013744,15.859122,4.127134,1.138150,1.079064,1.370163,1.392128,0.293845
6,NCT OF DELHI,57.802154,33.947194,8.250652,61.224134,30.869822,7.906043,1.152130,1.087735,1.266985,1.202350,0.587541
7,RAJASTHAN,87.651767,10.540008,1.808225,90.656045,8.241115,1.102840,1.077387,1.041683,1.377928,1.766491,0.268230
8,UTTAR PRADESH,87.260869,11.258479,1.480652,89.967989,8.942479,1.089532,1.095967,1.062989,1.379809,1.489397,0.234998
9,BIHAR,82.601666,15.503511,1.894823,85.310920,13.376194,1.312886,1.089457,1.054859,1.262722,1.572359,0.302109
10,SIKKIM,33.964775,35.259541,30.775683,38.902705,32.584946,28.512349,1.123694,0.981064,1.215928,1.212894,0.883229
11,ARUNACHAL PRADESH,32.987119,33.862297,33.150584,39.157529,33.687959,27.154513,1.065835,0.897881,1.071350,1.301185,0.854432
12,NAGALAND,35.402367,34.675874,29.921759,40.470492,35.323682,24.205826,1.074221,0.939696,1.054521,1.327886,0.800518
13,MANIPUR,47.150396,28.086051,24.763553,55.664024,25.949614,18.386362,1.015085,0.859831,1.098657,1.367160,0.588871
14,MIZORAM,68.638255,25.110788,6.250957,74.986666,21.644979,3.368354,1.024862,0.938097,1.188964,1.901929,0.385357
15,TRIPURA,61.934052,31.176029,6.889920,69.153134,26.988438,3.858428,1.041586,0.932852,1.203201,1.859939,0.402047
16,MEGHALAYA,70.433668,18.791057,10.775275,74.154219,18.104927,7.740853,1.011372,0.960629,1.049701,1.407831,0.447788
17,ASSAM,49.939254,33.521353,16.539392,57.545326,31.212731,11.241943,1.044105,0.906100,1.121331,1.536110,0.518246
18,WEST BENGAL,81.237939,14.939390,3.822671,85.959256,11.585782,2.454962,1.052667,0.994849,1.357371,1.639129,0.274767
19,JHARKHAND,67.666201,26.628294,5.705505,71.811203,24.283665,3.905132,1.054335,0.993478,1.156132,1.540412,0.391862
20,ODISHA,62.919350,21.244381,15.836269,71.296588,18.270610,10.432802,1.021677,0.901631,1.187967,1.550834,0.414623
21,CHHATTISGARH,85.812858,12.276817,1.910325,87.700089,10.904263,1.395648,1.009486,0.987763,1.136553,1.381757,0.300051
22,MADHYA PRADESH,85.444394,12.539962,2.015643,87.622320,10.950205,1.427474,1.074192,1.047492,1.230144,1.516797,0.297581
23,GUJARAT,52.178027,31.368958,16.453016,62.579669,25.712239,11.708092,1.087840,0.907025,1.327166,1.528707,0.459303
24,DAMAN & DIU,52.588472,32.870041,14.541487,51.187786,35.098875,13.713339,1.617079,1.661328,1.514392,1.714734,0.847482
25,DADRA & NAGAR HAVELI,41.571532,35.587841,22.840628,42.799218,39.021267,18.179514,1.292173,1.255107,1.178476,1.623478,0.704064
26,MAHARASHTRA,44.997805,35.333793,19.668401,53.104927,31.618783,15.276290,1.075959,0.911701,1.202378,1.385310,0.579031
27,ANDHRA PRADESH,71.269144,19.691771,9.039086,77.717971,16.330260,5.951769,1.007203,0.923628,1.214531,1.529662,0.343464
28,KARNATAKA,57.913168,27.493410,14.593422,62.760652,26.243053,10.996295,1.027815,0.948429,1.076785,1.364035,0.493990
29,GOA,20.531428,25.984523,53.484049,25.109222,26.805624,48.085154,1.027432,0.840116,0.995960,1.142790,0.731286
30,LAKSHADWEEP,65.770009,14.802403,19.427588,76.985646,11.703349,11.311005,1.056555,0.902631,1.336331,1.814721,0.379594
31,KERALA,73.213891,15.966789,10.819320,77.729759,13.899303,8.370938,0.922247,0.868667,1.059429,1.191992,0.336203
32,TAMIL NADU,69.558557,26.539199,3.902244,73.852830,23.267420,2.879751,1.003580,0.945226,1.144700,1.359915,0.346070
33,PUDUCHERRY,65.130096,28.207330,6.662574,71.876269,23.267899,4.855833,0.963913,0.873442,1.168538,1.322563,0.354235
34,ANDAMAN & NICOBAR ISLANDS,29.818456,49.554643,20.626901,35.261381,47.372123,17.366496,1.141585,0.965370,1.194179,1.355907,0.814565

For Monolingual

In [18]:
output = {"state/ut": [], "male-percentage": [], "female-percentage": [], "p-value": []}
for idx, row in df.iterrows():
    output["state/ut"].append(row["state-name"])
    output["male-percentage"].append(row["percent-one_m"])
    output["female-percentage"].append(row["percent-one_f"])
    output["p-value"].append(row["pval"])
parta = pd.DataFrame(output).sort_values(by=['state/ut'])
parta.to_csv("../Final Outputs/gender-india-a.csv", index = False)

For Bilingual

In [19]:
output = {"state/ut": [], "male-percentage": [], "female-percentage": [], "p-value": []}
for idx, row in df.iterrows():
    output["state/ut"].append(row["state-name"])
    output["male-percentage"].append(row["percent-two_m"])
    output["female-percentage"].append(row["percent-two_f"])
    output["p-value"].append(row["pval"])
parta = pd.DataFrame(output).sort_values(by=['state/ut'])
parta.to_csv("../Final Outputs/gender-india-b.csv", index = False)

For Trilingual

In [20]:
output = {"state/ut": [], "male-percentage": [], "female-percentage": [], "p-value": []}
for idx, row in df.iterrows():
    output["state/ut"].append(row["state-name"])
    output["male-percentage"].append(row["percent-three_m"])
    output["female-percentage"].append(row["percent-three_f"])
    output["p-value"].append(row["pval"])
parta = pd.DataFrame(output).sort_values(by=['state/ut'])
parta.to_csv("../Final Outputs/gender-india-c.csv", index = False)