In [1]:
import pandas as pd

In [2]:
cols = ["state-code", "area-name", "age-groups", "persons", "males", "females"]
df1 = pd.read_excel("../Data/DDW-0000C-14.xls", skiprows = [0,1,2,3,5,6], names = cols, usecols = [1, 3, 4, 5, 6, 7])
df1.replace(["All ages"], ["Total"], inplace = True)

In [3]:
#Adding age group "30-49"
temp = df1[(df1["age-groups"] == "30-34") | (df1["age-groups"] == "35-39") | (df1["age-groups"] == "40-44") | (df1["age-groups"] == "45-49")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["30-49" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [4]:
#Adding age group "50-69"
temp = df1[(df1["age-groups"] == "50-54") | (df1["age-groups"] == "55-59") | (df1["age-groups"] == "60-64") | (df1["age-groups"] == "65-69")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["50-69" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [5]:
#Adding age group "70+"
temp = df1[(df1["age-groups"] == "70-74") | (df1["age-groups"] == "75-79") | (df1["age-groups"] == "80+")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["70+" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [6]:
cols = ["state-code", "area-name", "Total", "age-groups", "males_two", "females_two"]
df2 = pd.read_excel("../Data/DDW-C18-0000.xlsx", skiprows = [0,1,2,3,5], usecols = [0, 2, 3, 4, 6, 7], names = cols)
df2 = df2[df2['Total'] == "Total"]
df2 = df2[df2["age-groups"] != "Age not stated"]
df2.reset_index(inplace = True)

In [7]:
output = {"state/ut": [], "age-group-males": [], "ratio-males": [], "age-group-females": [], "ratio-females": []}
scodes = df2["state-code"].unique().tolist()
for code in scodes:
    temp = df2[df2["state-code"] == code]
    output["state/ut"].append(temp["state-code"].unique()[0])
    agegrp_m = ""
    maxpercent_m = 0
    agegrp_f = ""
    maxpercent_f = 0
    for idx, row in temp.iterrows():
        tot_m = df1["males"][(df1["state-code"] == code) & (df1["age-groups"] == row['age-groups'])].tolist()[0]
        percent = (tot_m - row["males_two"]) / tot_m
        if percent > maxpercent_m:
            maxpercent_m = percent
            agegrp_m = row["age-groups"]
        
        tot_f = df1["females"][(df1["state-code"] == code) & (df1["age-groups"] == row['age-groups'])].tolist()[0]
        percent = (tot_f - row["females_two"]) / tot_f
        if percent > maxpercent_f:
            maxpercent_f = percent
            agegrp_f = row["age-groups"]
    output["age-group-males"].append(agegrp_m)
    output["ratio-males"].append(maxpercent_m)
    output["age-group-females"].append(agegrp_f)
    output["ratio-females"].append(maxpercent_f)

In [8]:
df = pd.DataFrame(output).sort_values(by=['state/ut'])
df.to_csv("../Final Outputs/age-gender-c.csv", index = False)

In [9]:
df

    state/ut age-group-males  ratio-males age-group-females  ratio-females
0          0             5-9     0.876821               5-9       0.876585
1          1             5-9     0.685737               70+       0.781736
2          2             5-9     0.887130               70+       0.922298
3          3             5-9     0.801164               70+       0.848261
4          4             5-9     0.713938               5-9       0.725435
5          5             5-9     0.903684               5-9       0.903566
6          6             5-9     0.906105               5-9       0.907915
7          7             5-9     0.844588               5-9       0.844506
8          8             5-9     0.939905               70+       0.941447
9          9             5-9     0.954013               5-9       0.953154
10        10             5-9     0.879816               5-9       0.880132
11        11             5-9     0.625837               5-9       0.619293
12        12             5-9     0.535681               70+       0.625470
13        13             5-9     0.672980               70+       0.693477
14        14             5-9     0.814030               5-9       0.813489
15        15             5-9     0.895288               5-9       0.898601
16        16             5-9     0.803502               70+       0.806495
17        17             5-9     0.910251               5-9       0.906486
18        18             5-9     0.737461               5-9       0.735775
19        19             5-9     0.928575               5-9       0.929845
20        20             5-9     0.796171               5-9       0.796685
21        21             5-9     0.838857               70+       0.874292
22        22             5-9     0.899148               5-9       0.903885
23        23             5-9     0.922551               5-9       0.919569
24        24             5-9     0.867415               5-9       0.871166
25        25             5-9     0.768722               5-9       0.776100
26        26             5-9     0.551498               70+       0.564497
27        27             5-9     0.768407               5-9       0.769615
28        28             5-9     0.864464               70+       0.869306
29        29             5-9     0.750905               5-9       0.750633
30        30             5-9     0.479240               5-9       0.475242
31        31             5-9     0.969203               5-9       0.974311
32        32             5-9     0.951883               5-9       0.950733
33        33             5-9     0.857816               5-9       0.856116
34        34             5-9     0.887297               5-9       0.887621
35        35             5-9     0.541645               70+       0.585013