In [1]:
import pandas as pd

In [2]:
cols = ["state-code", "area-name", "age-groups", "persons", "males", "females"]
df1 = pd.read_excel("../Data/DDW-0000C-14.xls", skiprows = [0,1,2,3,5,6], names = cols, usecols = [1, 3, 4, 5, 6, 7])
df1.replace(["All ages"], ["Total"], inplace = True)

In [3]:
#Adding age group "30-49"
temp = df1[(df1["age-groups"] == "30-34") | (df1["age-groups"] == "35-39") | (df1["age-groups"] == "40-44") | (df1["age-groups"] == "45-49")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["30-49" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [4]:
#Adding age group "50-69"
temp = df1[(df1["age-groups"] == "50-54") | (df1["age-groups"] == "55-59") | (df1["age-groups"] == "60-64") | (df1["age-groups"] == "65-69")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["50-69" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [5]:
#Adding age group "70+"
temp = df1[(df1["age-groups"] == "70-74") | (df1["age-groups"] == "75-79") | (df1["age-groups"] == "80+")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["70+" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [6]:
cols = ["state-code", "area-name", "Total", "age-groups", "persons", "males", "females"]
df2 = pd.read_excel("../Data/DDW-C18-0000.xlsx", skiprows = [0,1,2,3,5], usecols = [0, 2, 3, 4, 8, 9, 10], names = cols)
df2 = df2[df2['Total'] == "Total"]

In [7]:
output = {"state/ut": [], "age-group-males": [], "ratio-males": [], "age-group-females": [], "ratio-females": []}
scodes = df2["state-code"].unique().tolist()
for code in scodes:
    temp = df2[df2["state-code"] == code]
    output["state/ut"].append(temp["state-code"].unique()[0])
    agegrp_m = ""
    maxpercent_m = 0
    agegrp_f = ""
    maxpercent_f = 0
    for idx, row in temp.iterrows():
        tot_m = df1["males"][(df1["state-code"] == code) & (df1["age-groups"] == row['age-groups'])].tolist()[0]
        percent = row["males"]/tot_m
        if percent > maxpercent_m:
            maxpercent_m = percent
            agegrp_m = row["age-groups"]
        
        tot_f = df1["females"][(df1["state-code"] == code) & (df1["age-groups"] == row['age-groups'])].tolist()[0]
        percent = row["females"]/tot_f
        if percent > maxpercent_f:
            maxpercent_f = percent
            agegrp_f = row["age-groups"]
    output["age-group-males"].append(agegrp_m)
    output["ratio-males"].append(maxpercent_m)
    output["age-group-females"].append(agegrp_f)
    output["ratio-females"].append(maxpercent_f)

In [8]:
df = pd.DataFrame(output).sort_values(by=['state/ut'])
df.to_csv("../Final Outputs/age-gender-a.csv", index = False)

In [9]:
df

    state/ut age-group-males  ratio-males age-group-females  ratio-females
0          0           20-24     0.122734             20-24       0.107109
1          1           20-24     0.317513             20-24       0.272289
2          2           20-24     0.083464             15-19       0.080732
3          3           15-19     0.446176             15-19       0.472069
4          4             70+     0.538880             15-19       0.424175
5          5           20-24     0.034273             20-24       0.027630
6          6           20-24     0.073585             15-19       0.073951
7          7             70+     0.203584             50-69       0.120097
8          8           20-24     0.032170             15-19       0.025576
9          9           20-24     0.025913             20-24       0.022732
10        10           20-24     0.031443             15-19       0.028679
11        11           15-19     0.437026             15-19       0.479614
12        12           15-19     0.480533             15-19       0.471169
13        13           25-29     0.421940             20-24       0.390252
14        14           30-49     0.352224             20-24       0.291086
15        15           30-49     0.101009             25-29       0.056303
16        16           25-29     0.100840             20-24       0.065508
17        17           30-49     0.183675             20-24       0.128277
18        18           30-49     0.239542             15-19       0.185952
19        19           50-69     0.060462             20-24       0.037846
20        20           20-24     0.083440             15-19       0.069338
21        21           20-24     0.249141             15-19       0.210129
22        22           30-49     0.026553             20-24       0.020936
23        23           20-24     0.031203             15-19       0.028724
24        24           15-19     0.258126             15-19       0.218742
25        25           50-69     0.223430             15-19       0.259195
26        26           10-14     0.329725             15-19       0.358171
27        27           20-24     0.285348             15-19       0.262631
28        28           20-24     0.143784             15-19       0.127302
29        29           25-29     0.193887             20-24       0.166122
30        30           15-19     0.662455             15-19       0.701468
31        31           25-29     0.266986             20-24       0.257070
32        32           20-24     0.167393             20-24       0.171422
33        33           25-29     0.048127             20-24       0.043725
34        34           50-69     0.097906             20-24       0.077331
35        35           15-19     0.277134             15-19       0.298794