In [1]:
import pandas as pd

In [2]:
cols = ["state-code", "area-name", "age-groups", "persons", "males", "females"]
df1 = pd.read_excel("../Data/DDW-0000C-14.xls", skiprows = [0,1,2,3,5,6], names = cols, usecols = [1, 3, 4, 5, 6, 7])
df1.replace(["All ages"], ["Total"], inplace = True)

In [3]:
#Adding age group "30-49"
temp = df1[(df1["age-groups"] == "30-34") | (df1["age-groups"] == "35-39") | (df1["age-groups"] == "40-44") | (df1["age-groups"] == "45-49")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["30-49" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [4]:
#Adding age group "50-69"
temp = df1[(df1["age-groups"] == "50-54") | (df1["age-groups"] == "55-59") | (df1["age-groups"] == "60-64") | (df1["age-groups"] == "65-69")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["50-69" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [5]:
#Adding age group "70+"
temp = df1[(df1["age-groups"] == "70-74") | (df1["age-groups"] == "75-79") | (df1["age-groups"] == "80+")]
temp = temp.groupby(["state-code", "area-name"], as_index=False).agg('sum')
agegrp = ["70+" for i in range(len(temp))]
temp["age-groups"] = agegrp
df1 = df1.append(temp, ignore_index = True)

In [6]:
cols = ["state-code", "area-name", "Total", "age-groups", "persons_two", "males_two", "females_two", "persons_three", "males_three", "females_three"]
df2 = pd.read_excel("../Data/DDW-C18-0000.xlsx", skiprows = [0,1,2,3,5], usecols = [0, 2, 3, 4, 5, 6, 7, 8, 9, 10], names = cols)
df2 = df2[df2['Total'] == "Total"]
df2 = df2[df2["age-groups"] != "Age not stated"]
df2.reset_index(inplace = True)
#Getting exact two language speaking males and females count
df2["person_exact_two"] = [df2["persons_two"][i]-df2["persons_three"][i] for i in range(df2.shape[0])]
df2["males_exact_two"] = [df2["males_two"][i]-df2["males_three"][i] for i in range(df2.shape[0])]
df2["females_exact_two"] = [df2["females_two"][i]-df2["females_three"][i] for i in range(df2.shape[0])]

In [7]:
output = {"state/ut": [], "age-group-males": [], "ratio-males": [], "age-group-females": [], "ratio-females": []}
scodes = df2["state-code"].unique().tolist()
for code in scodes:
    temp = df2[df2["state-code"] == code]
    output["state/ut"].append(temp["state-code"].unique()[0])
    agegrp_m = ""
    maxpercent_m = 0
    agegrp_f = ""
    maxpercent_f = 0
    for idx, row in temp.iterrows():
        tot_m = df1["males"][(df1["state-code"] == code) & (df1["age-groups"] == row['age-groups'])].tolist()[0]
        percent = row["males_exact_two"]/tot_m
        if percent > maxpercent_m:
            maxpercent_m = percent
            agegrp_m = row["age-groups"]
        
        tot_f = df1["females"][(df1["state-code"] == code) & (df1["age-groups"] == row['age-groups'])].tolist()[0]
        percent = row["females_exact_two"]/tot_f
        if percent > maxpercent_f:
            maxpercent_f = percent
            agegrp_f = row["age-groups"]
    output["age-group-males"].append(agegrp_m)
    output["ratio-males"].append(maxpercent_m)
    output["age-group-females"].append(agegrp_f)
    output["ratio-females"].append(maxpercent_f)

In [8]:
df = pd.DataFrame(output).sort_values(by=['state/ut'])
df.to_csv("../Final Outputs/age-gender-b.csv", index = False)

In [9]:
df

    state/ut age-group-males  ratio-males age-group-females  ratio-females
0          0           20-24     0.266027             20-24       0.245006
1          1           10-14     0.491022             10-14       0.473909
2          2           25-29     0.168465             20-24       0.153183
3          3           10-14     0.264767             10-14       0.265602
4          4           30-49     0.289201               70+       0.305369
5          5           20-24     0.242618             20-24       0.203420
6          6           20-24     0.259946             20-24       0.243538
7          7           20-24     0.434504             20-24       0.432642
8          8           20-24     0.144275             15-19       0.121282
9          9           20-24     0.178002             20-24       0.155031
10        10           20-24     0.201162             15-19       0.188476
11        11           30-49     0.404535             30-49       0.373791
12        12           10-14     0.417198             10-14       0.420322
13        13           15-19     0.412106             30-49       0.442613
14        14           15-19     0.351708             15-19       0.345547
15        15           20-24     0.352536             15-19       0.347105
16        16           25-29     0.374674             15-19       0.361689
17        17           20-24     0.268866             15-19       0.275806
18        18           25-29     0.402302             10-14       0.390182
19        19           25-29     0.189622             20-24       0.154762
20        20           20-24     0.327151             15-19       0.322885
21        21           25-29     0.272898             10-14       0.255198
22        22           25-29     0.149943             20-24       0.136696
23        23           20-24     0.166342             15-19       0.154542
24        24           15-19     0.418807             15-19       0.398439
25        25           10-14     0.426129             15-19       0.499443
26        26           50-69     0.480737             10-14       0.470213
27        27           15-19     0.433263             15-19       0.428874
28        28           20-24     0.268427             15-19       0.254361
29        29           20-24     0.324414             15-19       0.317763
30        30           10-14     0.344619             10-14       0.339599
31        31           25-29     0.208293             20-24       0.203771
32        32           20-24     0.255765             20-24       0.258137
33        33           20-24     0.381437             15-19       0.383648
34        34           20-24     0.441125             15-19       0.436039
35        35           10-14     0.564552             10-14       0.560340